services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      DB_HOST: postgres
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_PORT: 5432

      JWT_SECRET_KEY: zU&4CXb9dEXLEsHJS8Yk
      JWT_ALGORITHM: HS256
      JWT_EXPIRE_MINUTES: 30
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-next
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
      API_URL: http://backend:8000
    depends_on:
      - backend

  postgres:
    image: postgres:17
    container_name: postgres-database
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d